# name: Git config
#
# The portable half of the git config is tracked as config/shared/.gitconfig and
# symlinked by step 10. This step writes the half that cannot be: the path to
# 1Password's SSH signing binary, which lives somewhere different on every OS.
#
# It goes in ~/.config/git/config, which git reads in addition to ~/.gitconfig
# (before it, so the tracked file wins any clash). An [include] in the tracked
# file cannot work: git resolves a relative include against the including
# file's directory — this repo, via the symlink — and does not expand ~/ there.

has git || die "git is missing"

signer=""
case $OS in
  macos) signer="/Applications/1Password.app/Contents/MacOS/op-ssh-sign" ;;
  linux) signer="/opt/1Password/op-ssh-sign" ;;
esac

if [ -n "$signer" ] && [ -x "$signer" ]; then
  mkdir -p "$HOME/.config/git"
  cat >"$HOME/.config/git/config" <<LOCAL
# Generated by ./install.sh — machine-specific, not tracked, edits are lost.
# Read by git in addition to ~/.gitconfig, which is the tracked one.
[gpg "ssh"]
	program = "$signer"
LOCAL
  ok "signing via $(basename "$signer")"
else
  mkdir -p "$HOME/.config/git"
  : >"$HOME/.config/git/config"
  info "no 1Password op-ssh-sign here — fine, commit signing is off in the"
  info "tracked config. To sign on this machine, set gpg.format, user.signingkey"
  info "and commit.gpgsign in ~/.config/git/config, which is untracked."
fi

# No global identity is tracked on purpose (see the README) — it is set per
# repository. So an empty one here is the expected state, not a problem.
name=$(git config --get user.name 2>/dev/null || true)
if [ -n "$name" ]; then
  ok "global identity: $name <$(git config --get user.email)>"
else
  ok "no global identity, as intended — set user.email per repo, or by hand"
fi

# This, on the other hand, would mean step 10 never ran.
[ -L "$HOME/.gitconfig" ] || warn "~/.gitconfig is not a symlink — run ./install.sh symlinks"

if [ "$(git config --get core.pager)" = delta ]; then
  ok "delta is the pager"
else
  warn "core.pager is not delta — is ~/.gitconfig linked?"
fi
