# name: Git config
#
# The portable half of the git config is tracked as config/shared/.gitconfig and
# symlinked by step 10. This step writes the half that cannot be: the path to
# 1Password's SSH signing binary, which lives somewhere different on every OS.
#
# It goes in ~/.config/git/config, which git reads in addition to ~/.gitconfig
# (before it, so the tracked file wins any clash). An [include] in the tracked
# file cannot work: git resolves a relative include against the including
# file's directory — this repo, via the symlink — and does not expand ~/ there.

has git || die "git is missing"

signer=""
case $OS in
  macos) signer="/Applications/1Password.app/Contents/MacOS/op-ssh-sign" ;;
  linux) signer="/opt/1Password/op-ssh-sign" ;;
esac

# This file is yours too — a global identity goes here, for one — so the step
# owns exactly one key in it and edits that key in place with `git config
# --file`. It used to be rewritten from a heredoc, which silently deleted
# anything added by hand on every re-run.
local_cfg="$HOME/.config/git/config"
mkdir -p "$(dirname "$local_cfg")"
touch "$local_cfg"

# Drop the old generated header, which promised that edits would be lost.
if grep -q '^# Generated by ./install.sh' "$local_cfg"; then
  grep -v -e '^# Generated by ./install.sh' -e '^# Read by git in addition to ~/.gitconfig' \
    "$local_cfg" >"$local_cfg.tmp" && mv "$local_cfg.tmp" "$local_cfg"
fi

if [ -n "$signer" ] && [ -x "$signer" ]; then
  git config --file "$local_cfg" gpg.ssh.program "$signer"
  ok "signing via $(basename "$signer")"
else
  # Exit 5 means the key was not set, which is the usual case here.
  git config --file "$local_cfg" --unset gpg.ssh.program || [ $? -eq 5 ]
  info "no 1Password op-ssh-sign here — fine, commit signing is off in the"
  info "tracked config. To sign on this machine, set gpg.format, user.signingkey"
  info "and commit.gpgsign in ~/.config/git/config, which is untracked."
fi

# No global identity is tracked on purpose (see the README). Set one by hand in
# ~/.config/git/config, or per repository; this step leaves either alone.
name=$(git config --get user.name 2>/dev/null || true)
if [ -n "$name" ]; then
  ok "global identity: $name <$(git config --get user.email)>"
else
  ok "no global identity — set user.name/user.email in ~/.config/git/config, or per repo"
fi

# This, on the other hand, would mean step 10 never ran.
[ -L "$HOME/.gitconfig" ] || warn "~/.gitconfig is not a symlink — run ./install.sh symlinks"

if [ "$(git config --get core.pager)" = delta ]; then
  ok "delta is the pager"
else
  warn "core.pager is not delta — is ~/.gitconfig linked?"
fi
